project:
  type: website
  output-dir: docs
  
website:
  title: "My website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: FYP Project
      - href: Data Visualization.qmd
        text: Data Visualization
      - href: Reflection.qmd
        text: Reflection


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



